version: 0.2

env:
  variables:
     cfci_version: "v5"
     project: "valhalla"
     deployment_decriptor: "deployment.yaml"
     artfct_base: "https://repository.phdata.io/artifactory/cloudfoundation/releases/"

  parameter-store:
    bb_app_user: /CodeBuild/bb_codebuild_user
    bb_app_pwd: /CodeBuild/bb_codebuild_pwd
    artifactory_usr: /CodeBuild/cfgoldbuild/artifactory_usr
    artifactory_pwd: /CodeBuild/cfgoldbuild/artifactory_pwd
phases:
  install:
    runtime-versions:
       python: 3.7
    commands:
       - pip install --quiet -r $CODEBUILD_SRC_DIR/requirements.txt
  pre_build:
    commands:
       - curl -u$artifactory_usr:$artifactory_pwd -O $artfct_base$cfci_version.zip
       - unzip $cfci_version.zip
       - cp $cfci_version/* .
       - cp stack_parser.py $project
       - rm -rf $artfct_base$cfci_version.zip $cfci_version/
       - cd $project
  build:
    commands:
       - export stage="build"
       - chmod +x $CODEBUILD_SRC_DIR/build.sh
       - $CODEBUILD_SRC_DIR/build.sh
  post_build:
    commands:
      - export stage="post_build"
      - $CODEBUILD_SRC_DIR/build.sh